### ISSUE TITLE
Improved Diffuse Lighting Formula

### ISSUE THREAD

**Issue by PepperCode1** [XorDev/XorDevs-Default-Shaderpack#6]
I noticed that the diffuse lighting formula in `textured.vsh` can be improved.

The new formula is as follows:
`min(normal.x * normal.x * 0.6f + normal.y * normal.y * 0.25f * (3.0f + normal.y) + normal.z * normal.z * 0.8f, 1.0f);`
There is also a separate formula for the nether:
`min(normal.x * normal.x * 0.6f + normal.y * normal.y * 0.9f + normal.z * normal.z * 0.8f, 1.0f);`

I am leaving this here as a note since I do not have time to submit a pull request for these right now.

**Comment by XorDev** [comment]
Interesting, thanks
